remote_theme: WildCodeSchool/workshops-jekyll-theme

# disable the jekyll-titles-from-headings plugin, 
# so first h1 will not be used as prior title of you page
titles_from_headings:
  enabled: false

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default" # possible values: default or tic-tac

style: dev # possible values: dev, data, ciber, design or wild.
title: "IA Challenge 🤖 Intégrer une Card | partie 2"
description: "L'IA a-t-elle bien fait son travail ? Vérifiez le code HTML & CSS généré par une IA."
# type: ''
# main_image: '' # http or relative path to image
show_clone: true
show_toc: true
lang: fr